services:
  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


  ollama:
    image: ollama/ollama
    container_name: ollama_service
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: always

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq_service
    ports:
      - "5672:5672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    restart: always

  minio:
    image: quay.io/minio/minio
    container_name: minio_service
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    volumes:
      - minio:/data
    restart: always
    command: ["server", "/data", "--console-address", ":9001"]

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant_service
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant:/qdrant/storage
    restart: always

  docling:
    image: quay.io/docling-project/docling-serve
    ports:
      - "5001:5001"
    environment:
      - DOCLING_SERVE_ENABLE_UI=1
  api:
    build: .
    ports:
      - "8980:80"
    environment:
      - AUTH_SECRET_KEY=${AUTH_SECRET_KEY}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - AWS_HOST=${AWS_HOST}
      - OLLAMA_HOST=${OLLAMA_HOST}
      - QDRANT_HOST=${QDRANT_HOST}
      - DOCLING_HOST=${DOCLING_HOST}

  celery_worker:
    build: .
    command: celery -A app.tasks worker --loglevel=info -P solo
    depends_on:
      - rabbitmq
      - ollama
      - docling
    environment:
      - AUTH_SECRET_KEY=${AUTH_SECRET_KEY}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - AWS_HOST=${AWS_HOST}
      - OLLAMA_HOST=${OLLAMA_HOST}
      - QDRANT_HOST=${QDRANT_HOST}
      - DOCLING_HOST=${DOCLING_HOST}
volumes:
  pgdata:
  ollama:
    name: ollama
  rabbitmq:
  minio:
  qdrant:

