"""initial migration

Revision ID: d30f3b255e3f
Revises: 
Create Date: 2026-07-24 00:31:26.923923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd30f3b255e3f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bucket_name', sa.String(), nullable=False),
    sa.Column('original_file_name', sa.String(), nullable=False),
    sa.Column('extension', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('reply_to', sa.Integer(), nullable=True),
    sa.Column('agentic', sa.Boolean(), nullable=False),
    sa.Column('finished', sa.Boolean(), nullable=False),
    sa.Column('source_nodes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_chat',
    sa.Column('user.id', sa.Integer(), nullable=False),
    sa.Column('chat.id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat.id'], ['chat.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user.id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user.id', 'chat.id')
    )
    op.create_table('chat_document',
    sa.Column('chat.id', sa.Integer(), nullable=False),
    sa.Column('document.id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat.id'], ['chat.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document.id'], ['document.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat.id', 'document.id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_document')
    op.drop_table('user_chat')
    op.drop_table('message')
    op.drop_table('document')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('chat')
    # ### end Alembic commands ###
