name: CD
on: [push]
jobs:
  docker-compose: 
    name: docker-compose
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6
      - name: build-images
        run: docker-compose build
      - name: run-compose
        run: docker-compose up -d
